### ISSUE TITLE
Cross origin downloads broken in Firefox

### ISSUE THREAD

**Issue by steel** [sindresorhus/multi-download#10]
The homepage demo is broken in Firefox when you sent the files to be from a different origin.

**Comment by steel** [comment]
I'm using Firefox 42

**Comment by sindresorhus** [comment]
What URLs did you change it to? Please try harder when opening an issue.

**Comment by steel** [comment]
Try any url that sends back a file as an attachment.

I set your `data-files` to look like:

```
data-files="https://download.mozilla.org/?product=firefox-42.0-SSL&os=win&lang=en-US https://download.mozilla.org/?product=firefox-42.0-SSL&os=osx&lang=en-US"
```

This only downloads the OSX file, not the Windows file.
