### ISSUE TITLE
Not working in IE and Safari

### ISSUE THREAD

**Issue by Pranalid15** [sindresorhus/multi-download#11]
I have downloaded the multi download package and it works fine on chrome and firefox. But for some reason it doesn't work on IE and Safari. Where as the demo link on your git page works fine across all the browser. Is there anything that I have missed?

Can you please help me to resolve this issue. Thank you.

**Comment by jvanstan** [comment]
I'm also having the same issue in IE and Safari. Have you been able to resolve this issue?

**Comment by daslicht** [comment]
any solution ?
