### ISSUE TITLE
IE=8 compatibility mode

### ISSUE THREAD

**Issue by jackpoz** [sindresorhus/multi-download#12]
Using the function multiDownload() inside a page with IE=8 compatibility mode using Internet Explorer 11 downloads only the first file. It seems "frame.contentWindow.document.readyState" is still "interactive" even after the file has been saved.

IE 8 compatibility mode can be enabled adding
```
<meta http-equiv="X-UA-Compatible" content="IE=8" />
```
in <head> tag.

As a workaround I added a loop counter in "frame.contentWindow.document.readyState === 'complete'" check and executing the if body after the 10th loop, this seems to work and download all files whether the user is fast enough or not to open/save them while they pop up.

**Comment by sindresorhus** [comment]
IE8 compatibility mode is not supported.
