### ISSUE TITLE
Issue in Chrome 57 on Mac

### ISSUE THREAD

**Issue by queicherius** [sindresorhus/multi-download#15]
[Here is a screen capture of the issue](http://recordit.co/RDivgbMK1X)

When I download multiple files on Windows, it works as expected. However, on MacOS, it only downloads the first file and the rest of the downloads are stuck in the download queue (without actually showing up in the download queue).

Any pointers how to fix that behaviour? Is this a Chrome bug?

**Comment by pguth** [comment]
In my test on MacOS/Chrome (recent) I heard a bump sound shortly after the first download dialog opened. I could get to the second download by clicking really fast on 'save'.

**Comment by SamVerschueren** [comment]
When I clicked it, it asked me if I wanted to allow the website to download multiple files. I picked `Allowed` and it downloaded all the files like expected.

**Comment by queicherius** [comment]
The `Multiple Downloads` permission was already given to the page in previous tries, and it shows up in the Chrome settings. I tried removing and re-adding it, but to no avail. :(

**Comment by psing008** [comment]
I am having the exact same issue. Any ideas ?

**Comment by davidagee** [comment]
This issue arises when "Ask where to save each file before downloading" is enabled in the Chrome preferences. Unfortunately AFAIK there is no easy workaround to this. 

![image](https://user-images.githubusercontent.com/2498690/29233892-741e3816-7ea8-11e7-9d42-16f62ba08116.png)
