### ISSUE TITLE
multi-download only loading last file in Chrome 65

### ISSUE THREAD

**Issue by dominikschreiber** [sindresorhus/multi-download#19]
To reproduce, press the big button on https://sindresorhus.com/multi-download/. In Chrome 64 (stable), all three files are downloaded. In Chrome 65 (beta), only the last file (unicorn2.jpg.zip) is downloaded. Could be related to https://bugs.chromium.org/p/chromium/issues/detail?id=714373.

**Comment by boris-petrov** [comment]
@sindresorhus - Chrome 65 is stable and released and we also hit this problem. Can you help with this and release a new version?

@dominikschreiber - did you find any work-around for now until this is fixed?

**Comment by dstainer** [comment]
It appears that the <code>fallback</code> method provided allows the downloads to work. So I added a test for Chrome and then invoke it. It seems to work would definitely want to know if its failing for others.

**Comment by jamnikr** [comment]
https://github.com/sindresorhus/multi-download/pull/20

**Comment by dstainer** [comment]
@boris-petrov the function is [here](https://github.com/sindresorhus/multi-download/blob/master/browser.js#L4)

I trie the same changes that @jamnikr had in his PR an I wasn't able to get the same results. I'm sure it's operator error, I'll try again when I have a moment.

**Comment by jamnikr** [comment]
My solution doesn't work properly all the time I will try to fix it tomorrow

**Comment by jamnikr** [comment]
When I use iframe tag to download files it  works in all browsers. Thanks to this many lines of code has become useless. (https://github.com/sindresorhus/multi-download/pull/21)

**Comment by boris-petrov** [comment]
@jamnikr - unfortunately that PR didn't fix the problem on our side. :( Any ideas why? Still downloads just the first file.

**Comment by jamnikr** [comment]
What do you pass to download function (array, set)? Does problem occur in every browser?

**Comment by boris-petrov** [comment]
I pass an array of URLs like so: `multiDownload(urls)`.

What do you mean every browser? It was working fine with all versions of Chrome < 65, it broke on the first release of 65 and has been broken ever since.

**Comment by jamnikr** [comment]
So this is a very weird situation. I tested in Chrome 65 (Chrom in Ubuntu) and worked correctly.

**Comment by boris-petrov** [comment]
@jamnikr - ah, no, sorry, I installed your version but you haven't actually changed the `browser.js` build and so I was using the old release. Could you do that in your fork?

**Comment by mariogillazaro** [comment]
@jamnikr why your changes haven't been merged? How can I test this? How can I help?

**Comment by jamnikr** [comment]
@boris-petrov thank you for information. I built and made new pull request https://github.com/sindresorhus/multi-download/pull/22

**Comment by ameesme** [comment]
The fallback works when you can force the browser to download a file on the server-side through content-disposition. This does not work when downloading files from the local filesystem or blobs.

**Comment by dseeker** [comment]
@boris-petrov non-action is a shaky solution. 
I just encountered this problem because my chrome is still Version 65.0.3325.181 (Official Build) (64-bit). If the user has this situation, even for the next month or two while all users update, there will be many occasions where this crucial function will not work. In my situation it's a media asset purchase service, if the user buys 10 clips and just downloads 1, it will be a big support headache. 

perhaps some targeted version degradation for the fallback mechanism?

**Comment by boris-petrov** [comment]
@dseeker - as you see from the pull-request that I've made, I explicitly check for Chrome 65 and use the fallback. Otherwise I use the old code.

**Comment by dseeker** [comment]
is this fix already on npm?

**Comment by boris-petrov** [comment]
@dseeker - no, @sindresorhus doesn't seem to read this thread unfortunately. :( You can use something like `"multi-download": "boris-petrov/multi-download#ec6734a402929c7046b73fdfe2d249f22e1294ac"` in `package.json`.

**Comment by ameesme** [comment]
This unfortunately doesn't work with filesystem- or Blob-URLs. Right now, the only solution to this problem seems to be a **dirty** fix, by just adding a `setTimeout` to each file being downloaded.

```javascript
for (let fileIteration = 0; fileIteration < fileUrlArray.length; fileIteration += 1) {
  setTimeout(() => {
    multiDownload([fileUrlArray[fileIteration]]);
  }, fileIteration * 200);
}
 ```

It for sure is dirty, but it works on Chrome version 66.0.3359.

**Comment by sindresorhus** [comment]
Closing as it's fixed in Chrome 66.
