### ISSUE TITLE
[bug] firefox multi-download seems to be broken for different origin

### ISSUE THREAD

**Issue by stryju** [sindresorhus/multi-download#2]
if urls are from different domains, firefox seems to only initiate 1st download and ignore the rest

sample: http://jsbin.com/veley/1/edit

it doesn't occur for the "same origin" - some kind of weird CORS protection? :confounded:

**Comment by gus4no** [comment]
This seems to be happening to with internet explorer, I even increased the delay to 500ms and it doesn't work in version 11.

The only thing I noticed is that I'm getting an `Access Denied` exception in the JS console.

**Comment by stryju** [comment]
IE11 was not out there, when this issue was filed - mind creating a new one so we can track it accordingly?

**Comment by gus4no** [comment]
Sure!
