### ISSUE TITLE
Add a transpiled ES5 version in NPM

### ISSUE THREAD

**Issue by boris-petrov** [sindresorhus/multi-download#28]
Thank you for the new version!

We build our frontend twice - for new ES6+ browsers and for old ES5 ones. For the second ones we need our dependencies to also be ES5-compatible. Most libraries that have an ES6 build also include an ES5 one in their distribution for exactly the usecases like ours. Is it possible for you to do the same for `multi-download`? Thanks!

**Comment by sindresorhus** [comment]
Sorry, I'm not interested in the overhead of adding a built-step.
