### ISSUE TITLE
为啥pdf无法下载。

### ISSUE THREAD

**Issue by jsqfengbao** [sindresorhus/multi-download#29]

**Comment by sindresorhus** [comment]
Sorry, English-only.

**Comment by jsqfengbao** [comment]
why pdf download failed?


------------------ 原始邮件 ------------------
发件人: "Sindre Sorhus"<notifications@github.com>;
发送时间: 2019年6月20日(星期四) 晚上7:49
收件人: "sindresorhus/multi-download"<multi-download@noreply.github.com>;
抄送: "金双齐"<jsqfengbao@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [sindresorhus/multi-download] 为啥pdf无法下载。 (#29)




Sorry, English-only.
