### ISSUE TITLE
iOS is not working

### ISSUE THREAD

**Issue by nezkal** [sindresorhus/multi-download#30]
Hi,

I've tried to use that on iOS, but the multiple files download is not working, I've done it on Google Chrome and Safari.

Do you know any information about it ?

Thank you so much.

**Comment by montaserfzy** [comment]
is this solved?

**Comment by statler** [comment]
Would like to know this too

**Comment by bartosz-szczecinski-dragon** [comment]
FYI it's not working on newest iOS - it only allows you to fetch the first file.

**Comment by cenoura** [comment]
I've just tested on iOS 14.5 and it worked as expected.
I just needed to confirm each file download, but it looks like this is a Safari behavior.

![image](https://user-images.githubusercontent.com/1128688/119276036-e72c9000-bbee-11eb-8e88-3fd2279fefdd.jpeg)

@sindresorhus I think you can close this issue 🙂
