### ISSUE TITLE
Rename files on download

### ISSUE THREAD

**Issue by Porco-Rosso** [sindresorhus/multi-download#4]
Is it possible to rename a file on download? 
It is doable with download attribute - http://stackoverflow.com/a/15970037/257815

It would be really great if this was possible as an option!

**Comment by sindresorhus** [comment]
Why?

**Comment by Porco-Rosso** [comment]
I am serving files based on urls fetched by an api, the filenames are jibberish and so I would like to rename them before downloading.

**Comment by sindresorhus** [comment]
Ok, I guess an option would be ok then. Don't really care about this myself, so PR welcome ;)
