### ISSUE TITLE
Not working on chrome

### ISSUE THREAD

**Issue by gus4no** [sindresorhus/multi-download#5]
Hi there, I've trying to use this but somehow it's not working on chrome, well it kind off works, it only downloads one file, any idea on why is this? You can test this with the demo, sometimes it downloads the first item in the list, sometimes the second one and some times the third, speaking of your demo of course.

**Comment by sindresorhus** [comment]
Works for me in latest Chrome. Please read the caveat with Chrome: https://github.com/sindresorhus/multi-download#caveats

**Comment by gus4no** [comment]
I think there's a corner case, I just found out that I had default settings in chrome and if the 'Ask me where to save files' checkbox is checked it doesn't work! I think I read something about finding out when the dialog is gone so I'll do some research and try to submit a PR to fix this
