### ISSUE TITLE
Cross domain files not working in IE

### ISSUE THREAD

**Issue by gus4no** [sindresorhus/multi-download#6]
if urls are from different domains, IE 11 seems to only initiate 1st download and ignore the rest, it doesn't occur for the "same origin"  and console shows an uncaught exception `AccessDenied` for the iframes, this is al CORS related.

**Comment by gus4no** [comment]
The ugliest 'solution' I came up with so far is running a `window.open(file, '_blank')` in IE only if it's from different domains, since content has header `Content-Disposition: attachment;` the new tab would close automatically

**Comment by sindresorhus** [comment]
Sorry, I have no intention to support IE.
